# Generated by Django 6.0.6 on 2026-06-25 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='acesso_upscale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='limite_diario',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='limite_tamanho_arquivo_mb',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='prioridade_fila',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuarioassinatura',
            name='data_ultimo_reset_diario',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioassinatura',
            name='status_assinatura',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarioassinatura',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuarioassinatura',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuarioassinatura',
            name='uso_diario_atual',
            field=models.IntegerField(default=0),
        ),
    ]
