# Generated by Django 5.2.13 on 2026-06-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_assinatura_ativo_assinatura_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assinatura',
            options={'verbose_name': 'Plano de Assinatura', 'verbose_name_plural': 'Planos de Assinatura'},
        ),
        migrations.AlterModelOptions(
            name='usuarioassinatura',
            options={'verbose_name': 'Assinatura de Usuário', 'verbose_name_plural': 'Assinaturas de Usuários'},
        ),
    ]
