# Generated by Django 5.2.13 on 2026-04-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progresso', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_original', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.BigIntegerField()),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='processing.execucaolocal')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoProcessamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_final', models.FileField(upload_to='results/%Y/%m/%d/')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_processado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='processing.arquivoprocessado')),
            ],
        ),
        migrations.CreateModel(
            name='UsoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uso', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
