# Generated by Django 6.0.6 on 2026-06-25 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaolocal',
            name='formato_entrada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='execucaolocal',
            name='formato_saida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='execucaolocal',
            name='logs_de_erro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaolocal',
            name='parametros_processamento',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaolocal',
            name='status_detalhado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='execucaolocal',
            name='tempo_execucao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arquivoprocessado',
            name='arquivo_original',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='arquivoprocessado',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arquivoprocessado',
            name='tamanho',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execucaolocal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na Fila'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='resultadoprocessamento',
            name='arquivo_final',
            field=models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_original', models.CharField(max_length=255)),
                ('nome_interno_unico', models.CharField(max_length=255, unique=True)),
                ('extensao', models.CharField(max_length=10)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamanho', models.BigIntegerField()),
                ('hash_arquivo', models.CharField(blank=True, max_length=64, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('caminho_armazenamento', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arquivoprocessado',
            name='arquivo_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processamentos', to='processing.arquivo'),
        ),
        migrations.AddField(
            model_name='resultadoprocessamento',
            name='arquivo_final_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='processing.arquivo'),
        ),
    ]
